name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Tests with Docker Compose
        # This runs your existing stack. The volume mount in docker-compose.yml
        # ensures 'allure-results' are written back to the host runner.
        run: docker-compose up --abort-on-container-exit

      - name: Get Allure History
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure_report
        with:
          allure_results: allure-results
          allure_history: allure-history

      - name: Build GH Pages Site
        if: always()
        run: |
          mkdir -p site/report
          cp -r ${{ steps.allure_report.outputs.allure_report_path }}/* site/report/
          cp index.html site/

      - name: Deploy Report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./site
          force_orphan: true
